unishare/documents/urls.py
from django.conf.urls.defaults import *
from unishare.documents.models import Document 

info_dict = {
  'queryset': Document.objects.all(),
}

urlpatterns = patterns('',
      (r'^upload$', 'unishare.documents.views.upload'),
      (r'^captcha/', include('captcha.urls')),
)

unishare/urls.py
from django.conf.urls.defaults import *
from django.conf import settings 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
     (r'^captcha/', include('captcha.urls')),
     (r'^unishare/', include('unishare.documents.urls')),
     (r'^upload/', 'unishare.documents.views.upload'),
     (r'^about/', 'unishare.documents.views.about'),
     (r'^contact/', 'unishare.documents.views.contact'),
     (r'^school/(?P<school>[^/]+)/$', 'unishare.documents.views.school'),
     (r'^school/(?P<school>[^/]+)/course/(?P<course>[^/]+)/$', 'unishare.documents.views.school_course'),

    # Uncomment the admin/doc line below to enable admin documentation:
     (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     (r'^admin/', include(admin.site.urls)),
     (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'../static'}),
     (r'^uploads/documents/(?P<path>.*)$', 'django.views.static.serve', {'document_root':'../uploads/documents'}),
     (r'^$', 'unishare.documents.views.root')
)

unishare/documents/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.forms import ModelForm
from datetime import datetime
from time import time
from django import forms
from django.conf import settings
from tagging.fields import TagField
from tagging.models import Tag
from captcha.fields import CaptchaField
from os.path import splitext

import re

attachment_file_storage = FileSystemStorage(location=settings.UPLOAD_ROOT, base_url='documents')

# Create your models here.
class Document(models.Model):

    # Document specific
    name = models.CharField(max_length=200)
    year = models.CharField(max_length='200', blank=True)
    semester = models.CharField(max_length='200', blank=True)
    school = models.CharField(max_length='200', blank=False)
    course = models.CharField(max_length='200', blank=False)
    professor = models.CharField(max_length='200', blank=True)

    # Files specific
    local_file = models.CharField(max_length='200', blank=True)
    doc_file = models.FileField(upload_to='documents', storage=attachment_file_storage)
    file_loc = models.CharField(max_length='500', blank=True)
    mimetype = models.CharField(max_length='500', blank=True)

    # Meta specific
    date = models.DateTimeField('date uploaded', blank=True, default=datetime.now())
    approved = models.BooleanField(default=True, blank=True)
    featured = models.BooleanField(default=False, blank=True)

    tags = TagField()

    #blobs
    description = models.TextField(blank=False) 

    def save(self):
        super(Document, self).save()

        # New recording, let me know about it
        #if not self.approved:
        #    send_mail('New recording: ' + self.name, 'Public: \n ' + self.public_description + 'Private: \n' +         self.private_description, 'bigvagitabluntz420@gmail.com', ['rich@anomos.info'], fail_silently=False)

    def get_tags(self):
        return Tag.objects.get_for_object(self)
    
    def __unicode__(self):
        return self.name + ' - ' + self.course + ' - ' + self.school

class DocumentForm(ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Document

    #def __init__(self, bound_object=None, *args, **kwargs):
    #    super(RecordingForm, self).__init__(*args, **kwargs)
    #    self.bound_object = bound_object
    #    self.is_updating = False
    #    if self.bound_object:
    #        self.is_updating = True

    def clean(self):
        doc = self.cleaned_data.get('doc_file',None)
        if doc is None:
            self._errors['doc_file'] = "No file supplied!"
            raise forms.ValidationError('')

        if doc.size > 209715200:
            self._errors['doc_file'] = "File too big, son!"
            raise forms.ValidationError('')

        valid_content_types = ('text/html', 'text/plain', 'text/rtf',
                           'text/xml', 'application/msword',
                           'application/rtf', 'application/pdf', 'application/zip')
        valid_file_extensions = ('odt', 'pdf', 'doc', 'txt',
                             'html', 'rtf', 'htm', 'xhtml', 'zip')

        ext = splitext(doc.name)[1][1:].lower()
        if not ext in valid_file_extensions \
           and not doc.content_type in valid_content_types:
            self._errors['doc_file'] = "Sorry, this is not a valid file-type."
            raise forms.ValidationError('')

        return self.cleaned_data

    def save(self):
        self.bound_object = Document()
        uploaded_file = self.cleaned_data['doc_file']
        s_time = str(time())
        s_path = s_time + re.sub(r'[^a-zA-Z0-9._]+', '-', uploaded_file.name)
        stored_name = s_time + re.sub(r'[^a-zA-Z0-9._]+', '-', uploaded_file.name)
        self.bound_object.doc_file.save(stored_name, uploaded_file)
        self.bound_object.mimetype = uploaded_file.content_type
        self.bound_object.name = self.cleaned_data['name']
        self.bound_object.description = self.cleaned_data['description']
        self.bound_object.year = self.cleaned_data['year']
        self.bound_object.semester = self.cleaned_data['semester']
        self.bound_object.school = self.cleaned_data['school'].title()
        self.bound_object.course = self.cleaned_data['course'].upper()
        self.bound_object.professor = self.cleaned_data['professor']
        self.bound_object.date = datetime.now()
        self.bound_object.file_loc = settings.UPLOAD_HARD + s_path
        self.bound_object.save()

unishare/documents/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.shortcuts import get_object_or_404, render_to_response
from datetime import datetime
from tagging.models import Tag, TaggedItem
from django.views.decorators.csrf import csrf_exempt

from unishare.documents.models import Document, DocumentForm

## Dynamic content

def root(request):
    featureset = Document.objects.values_list('school', flat=True).order_by('school').distinct() 
    return render_to_response('all_schools.html', {'schools': featureset, 'cat': 'main', 'recent': get_most_recent()})

def school(request, school):
    featureset = Document.objects.values_list('course', flat=True).filter(school=school).order_by('course').distinct() 
    return render_to_response('by_school.html', {'classes': featureset, 'cat': 'main', 'school': school , 'recent': get_most_recent()})

def school_course(request, school, course):
    featureset = Document.objects.all().filter(school=school, course=course).order_by('name')
    return render_to_response('by_school_course.html', {'documents': featureset, 'cat': 'main', 'school': school, 'course': course , 'recent': get_most_recent()})

## Forms ##

def upload(request):
    if request.method == 'POST': # If the form has been submitted...
        form = DocumentForm(request.POST, request.FILES) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # XXX: Check filetypes, etc

            form.save()
            return HttpResponseRedirect('/') # Redirect after POST
        else:
            print "Shiiiiit"
    else:
        form = DocumentForm() # An unbound form

    return render_to_response('upload.html', {
        'form': form,
        'cat': 'upload' ,
        'recent': get_most_recent()
    })

## Static ##
def about(request):
    return render_to_response('about.html', {'cat': 'about' , 'recent': get_most_recent()})

def contact(request):
    return render_to_response('contact.html', {'cat': 'contact' , 'recent': get_most_recent()})

##Helper methods ##
def get_most_recent():
    return Document.objects.order_by('-date')[:5]

unishare/templates/about.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
							<h2 class="title"><a href="#">About</a></h2>
                            <p>Think of NotesHub as the best study group ever.
                            <p>NotesHub is a tool for sharing the schoolwork you make with with the rest of the world! If you're a college student, you can help out your classmates and your compatriots at other schools around the world by sharing the valuable notes you take, papers you write and problem sets you solve.
                            The point of college is to learn something, and we want to make learning easier! Technology has the power to make people so much smarter, but people aren't using it well enough yet! We think this is a good start.
                            <p>We know you've got some questions. <b>Won't this hurt my curved grade?</b>  If you're worried about sharing notes hurting your grade, wait until after your semester is over to upload them. If you're worried about the next years students getting better grades than you,
                            remember, that's a <i>good thing</i>. That means that the educational system is working - as we refine our teaching methods and improve our access to knowledge, each year <i>should</i> be better than the last.
                            <p><b>Isn't this cheating?</b> No! Cheating is taking somebody else's work and claiming it as your own. If you take an essay from NotesHub and put your own name on it, what you
                            are doing is wrong. It isn't wrong, however, to look at another student's work and <i>learn</i> from it. See what makes a good essay good and a bad essay bad. Take their <i>ideas</i>, not their words, and make them your own. Critique them and expand upon them. That's what education is supposed to be like.
                            <p>There are no barriers to entry on NotesHub - anybody can download and post anything, for free! There are no registrations, no required uploads, no pyramid schemes, no cash involved.
                            This is run as a completely free service, and all of the content is licensed under a Creative Commons license.
                            <p>We have no other motivation other than helping each other. We are not a startup company and we do not make any money off of advertising - we are just college students who want to make life a bit easier for everybody.
                            <p>In this regard, it is a lot like Wikipedia or the Linux kernel. In fact, even the code that runs code that runs this website is Free and Open Source (availble for download <a href="https://github.com/Miserlou/UniShare">on the GitHub page here</a>),
                            so that anybody can make their own content sharing website.
							<p>NotesHub is a project of the <a href="http://freeculture.org">Students for Free Culture</a>, an international student organization working to promote free culture ideals, such as liberalization of copyright laws, open government, cultural participation and access to information.
                            <p>You can help improve NotesHub in a number of different ways. The fastest thing you can do is simply to <a href="/upload">submit your own notes!</a>.
                            <p>The next best thing you can do is tell other people about NotesHub! Get on FaceBook, Twitter, AIM, Diaspora or whatever social services you use and tell your friends! The more people that know about NotesHub, the better it is for everybody!
                            <p>Finally, if you're <i>really</i> cool, you can write about NotesHub for your college newspaper. Get a dialog going - that's the whole idea here, to start a conversation about the ways that access to information is affecting our academic lives. 
                            <p>Thanks for using NotesHub!
							<br /><br /></br />
							</div>
						</div>
					</div>
				</div>
{% endblock %}

unishare/templates/all_schools.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
							<h2 class="title"><a href="#">Content From All Universities</a></h2>
							<div id="largelink">
                            <ul>
                            {% for school in schools %}
                                {% if school != '' and school != None %}
								<li>&bull; 	<a href="/school/{{school}}" >{{school}}</a></li>
                                {% endif %}
                            {% empty %}
                                Nothing uploaded yet! <br /><br /><br /><br /><br /><br /><br /><br />
                            {% endfor %}
                            </ul>
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
							</div>
						</div>
					</div>
				</div>
{% endblock %}

unishare/templates/by_school.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
							<h2 class="title"><a href="#">All Courses At {{school}}</a></h2>
							<div id="largelink">
                            <ul>
                            {% for class in classes %}
                                {% if class != '' and class != None %}
								<li>&bull; 	<a href="/school/{{school}}/course/{{class}}" >{{class}}</a></li>
                                {% endif %}
                            {% empty %}
                                Nothing uploaded yet! <br /><br /><br /><br /><br /><br /><br /><br />
                            {% endfor %}
                            </ul>
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
							</div>
						</div>
					</div>
				</div>
{% endblock %}

unishare/templates/by_school_course.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
							<h2 class="title"><a href="#">All {{course}} Documents At {{school}}</a></h2>
							<div id="largelink">
                            <ul>
                            {% for doc in documents %}
                            <li>&bull; 	<a href="{{doc.file_loc}}" >{{doc.name}}</a></li>
                            <table>
						
                                                <thead>
                                                </thead>

                                                <tbody>	

                                                <tr>
                                                <td>Name</td>
                                                <td><b>{{doc.name}}</b></td>
                                                </tr>
                                                <tr>
                                                <td>Description</td>
                                                <td><b>{{doc.description}}</b></td>
                                                </tr>
                                                <tr>
                                                <td>Professor</td>
                                                <td><b>{{doc.professor}}</b></td>
                                                </tr>
                                                <tr>
                                                <td>Semester</td>
                                                <td><b>{{doc.semester}} {{doc.year}}</b></td>
                                                </tr>
      

                                            </table><br /><br />
                            {% empty %}
                                Nothing uploaded yet! <br /><br /><br /><br /><br /><br /><br /><br />
                            {% endfor %}
                            </ul>
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
                        <br />
							</div>
						</div>
					</div>
				</div>
{% endblock %}

unishare/templates/contact.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
							<h2 class="title"><a href="#">Contact</a></h2>
                            <p>We'd love to get any feedback you have! Have you shown NotesHub to anybody - how did they react? Did your school newspaper give some press to NotesHub?
                            <p>You can email the main developer of NotesHub at rich [aatt] anomos [[dot]] info
                            <p>The source code to NotesHub is available here: <a href="https://github.com/Miserlou/UniShare">GitHub:Miserlou</a>
                            <p>To talk to other people interested in Free Culture, you can <a href="http://lists.freeculture.org/mailman/listinfo/discuss">subscribe to the Free Culture mailing list</a>.
                            <p>If you are a programmer and you want to work on this site or another Free Culture project, join the <a href="http://lists.freeculture.org/mailman/listinfo/fc-hackers">FC-Hackers Mailing List here</a>.
                            <p>We can also be found on the FreeNode IRC network in channel #freeculture
                            <br />
							</div>
						</div>
					</div>
				</div>
{% endblock %}

unishare/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : Vertebrate 
Version    : 1.0
Released   : 20100428
Description: A two-column fixed-width template suitable for small websites.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>NotesHub - Students Helping Students</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/static/default.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/static/jquery/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.slidertron-0.1.js"></script>
<LINK REL="SHORTCUT ICON" HREF="/static/favicon.ico">
</head>
<body>
<div id="wrapper">
<div id="header">
	<div id="logo">
		<h1><a href="/"> NotesHub </a></h1>
		<h2><a href="/">Students Helping Students</a></h2>
	</div>
	<!-- end div#logo -->
	<div id="menu">
		<ul>
			<li {% if cat == "main" %} class="active" {% endif %}><a href="/">Home</a></li>
			<li {% if cat == "upload" %} class="active" {% endif %}><a href="/upload">Upload</a></li>
			<li {% if cat == "about" %} class="active" {% endif %}><a href="/about">About</a></li>
			<li {% if cat == "contact" %} class="active" {% endif %}><a href="/contact">Contact</a></li>
		</ul>
	</div>
	<!-- end div#menu -->
</div>
<div>
	<div id="page">
		<div id="page-bgtop">
			<div id="content">

				{% block bodyblock %}

                {% endblock %}
			</div>
			<!-- end div#content -->
			<div id="sidebar">
				<div id="sidebar-bgtop">
					<div id="sidebar-bgbtm">
						<ul>
							<li id="search">
								<h2>About</h2>
                                    <b>NotesHub</b> is a place where students can share notes, papers and other educational materials with each other. The content here is 100% free and 100% submitted by students. If you are helped by this website, please consider <b><a href="/upload">submitting your own materials here</a>.</b>
							</li>
							<li>

						</ul>
					</div>
				</div>
			</div>
			<div id="sidebar">
				<div id="sidebar-bgtop">
					<div id="sidebar-bgbtm">
						<ul>
							<li id="search">
								<h2>Search</h2>
								<form method="get" action="">
									<fieldset>
										<input type="text" id="seach-text" name="s" value="" />
										<input type="submit" id="search-submit" value="Search" />
									</fieldset>
								</form>
							</li>
							<li>
								<h2>Recent Uploads</h2>
								<ul>
                                    {% for doc in recent %}
									<li><a href="/school/{{doc.school}}/course/{{doc.course}}"><b>{{doc.name}}</b> - {{doc.course}} - {{doc.school}}</a></li>
                                    {% endfor %}
								</ul>
							</li>

						</ul>
					</div>
				</div>
			</div>
			<!-- end div#sidebar -->
			<div style="clear: both; height: 1px"></div>
		</div>
	</div>
	<!-- end div#page -->
</div>
<!-- end div#wrapper -->
<div id="footer-wrapper">
	<div id="footer">
		<p id="legal">NotesHub is made by <a href="http://www.freeculture.org">Students for Free Culture</a></p>
		<p id="links">All content is available under the Creative Commons Attribution license.</p>
	</div>
</div>
<!-- end div#footer -->
</body>
</html>

unishare/templates/upload.html
{% extends "index.html" %}
{% block bodyblock %}
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
							<h2 class="title"><a href="#">Batch Upload</a></h2>
                            <p>If you have a lot of notes you want to share, but you don't want to upload them all individually, please send then in a Zip file to <a href="mailto:miserlou@gmail.com">the Staff</a>. Thank you!
                        </div>
                    </div>
</div>
<div class="post">
					<div class="post-bgtop">
						<div class="post-bgbtm">
    <script src="/static/jquery/jquery.watermarkinput.js" type="text/javascript"></script>
    <script type="text/javascript">
        jQuery(function($){
        $("#id_name").Watermark("ex, Mirror neurons");
        $("#id_desc").Watermark("ex, A mirror neuron is a neuron that fires both when an animal acts and when the animal observes the same action performed by another.");
        $("#id_year").Watermark("ex, 2007");
        $("#id_school").Watermark("ex, Boston University");
        $("#id_semester").Watermark("ex, Fall");
        $("#id_course").Watermark("ex, PS301");
        $("#id_professor").Watermark("ex, Dewees");
        });
    </script>
							<h2 class="title"><a href="#">Upload a Document!</a></h2>
                    <p><small>By uploading, you agree to release your documents under the Creative Commons attribution license, so that anybody may share it with anybody else.</small>
                    <p><form enctype="multipart/form-data" action="/upload/" method="post">
    {% csrf_token %}

		<div class="fieldWrapper">
          <div class="formlabel">
		    <label for="doc_file">Document</label>
          </div>
          <div class="formfield">
		    {{ form.doc_file}}
		    {{ form.doc_file.errors }}
		  </div>
	  </div><br>

		<div class="fieldWrapper">
          <div class="formlabel">
		  <label for="name">Title</label>
          </div>
          <div class="formfield">
		  {{ form.name}}
		  {{ form.name.errors }}
		  </div>
	  </div><br>

		<div class="fieldWrapper description">
          <div class="formlabel">
		    <label for="description">Description</label>
          </div>
          <div class="formfield">
		    {{ form.description}}
		    {{ form.description.errors }}
		  </div>
	  </div>

		<div class="fieldWrapper">
          <div class="formlabel">
		    <label for="year">Year</label>
          </div>
          <div class="formfield">
		    {{ form.year}}
		    {{ form.year.errors }}
		  </div>
	  </div><br>

		<div class="fieldWrapper">
          <div class="formlabel">
		    <label for="year">Semester</label>
          </div>
          <div class="formfield">
		    {{ form.semester}}
		    {{ form.semester.errors }}
		  </div>
	  </div><br>

		<div class="fieldWrapper">
          <div class="formlabel">
		    <label for="year">School</label>
          </div>
          <div class="formfield">
		    {{ form.school}}
		    {{ form.school.errors }}
		  </div>
	  </div><br>

		<div class="fieldWrapper">
          <div class="formlabel">
		  <label for="year">Course</label>
          </div>
          <div class="formfield">
		    {{ form.course}}
		    {{ form.course.errors }}
		  </div>
	  </div><br>

		<div class="fieldWrapper">
          <div class="formlabel">
		  <label for="year">Professor</label>
          </div>
          <div class="formfield">
		    {{ form.professor}}
		    {{ form.professor.errors }}
		  </div>
	  </div><br>

        {% if form.captcha %}
		<div class="fieldWrapper">
          <div class="formlabel">
		    <label for="location">Verification</label>
          </div>
          <div class="formfield">
		    {{ form.captcha}}
		    {{ form.captcha.errors }}
		  </div>
	  </div><br>
        {%endif%}
      <div class="fieldWrapper">
          <div class="formlabel">
		    <!--just a space-->
		    &nbsp;
          </div>
          <div class="formfield">
		    <input type="submit" value="Upload!" />
		  </div>
	  </div><br><br><br><br><br>
</form>
							</div>
						</div>
					</div>
				</div>
{% endblock %}